strictness: high
doc-warnings: false
test-warnings: false
autodetect: true
member-warnings: false

ignore-patterns:
  - (^|/)__init__.py$

pylint:
  options:
    max-line-length: 120
  disable:
    - abstract-method
    - use-list-literal
    - logging-fstring-interpolation
    - cyclic-import # https://github.com/PyCQA/pylint/issues/3525

pep8:
  options:
    max-line-length: 120
