image: python:3.7-slim-buster
pipelines:
  pull-requests:
    '**':
      - parallel:
        - step:
            name: "Run Static Code Analysis"
            caches:
              - pip
            script:
              - pip install -r requirements/dev.txt
              - prospector -t dodgy -t pep8 -t profile-validator -t mccabe -t pyflakes

        - step:
            name: "Run Tests"
            caches:
              - pip
            script:
              - pip install -r requirements/dev.txt
              - pip install coverage-badge
              - pytest --cov=snowshu tests/
              - coverage-badge -o coverage.svg -fq
              - pipe: atlassian/bitbucket-upload-file:0.1.2
                variables:
                  BITBUCKET_USERNAME: $BB_USER_NAME
                  BITBUCKET_APP_PASSWORD: $BB_APP_PASSWORD
                  FILENAME: 'coverage.svg'
            artifacts:
              - coverage.svg
