version: "3.5"

services:
  snowshu:
    image: snowshu-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/tmp/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: tail -f /dev/null
    networks:
      - snowshu
networks:
  snowshu:
    name: snowshu
    driver: bridge
